# Theming
font: JetBrainsMono Nerd Font 12
background: "#111c18"
color: "#fbf1c7"
border: "#8ec07c"
separator: " âžœ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: bottom-right # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0


# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "p"
    desc: Programs
    submenu:
      - key: "p"
        desc: 1Password
        cmd: uwsm-app -- 1password
      - key: "b"
        desc: Browser
        cmd: omarchy-launch-browser
      - key: "B"
        desc: Browser (private)
        cmd: omarchy-launch-browser --private
      - key: "f"
        desc: File manager
        cmd: uwsm-app -- nautilus --new-window
      - key: "m"
        desc: Music (Spotify)
        cmd: omarchy-launch-or-focus spotify
      - key: "o"
        desc: Obsidian
        cmd: omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
      - key: "g"
        desc: Signal
        cmd: omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
      - key: "a"
        desc: ChatGPT
        cmd: omarchy-launch-webapp "https://chatgpt.com"
      - key: "A"
        desc: Grok
        cmd: omarchy-launch-webapp "https://grok.com"
      - key: "c"
        desc: Calendar
        cmd: omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
      - key: "e"
        desc: Email
        cmd: omarchy-launch-webapp "https://app.hey.com"
      - key: "y"
        desc: YouTube
        cmd: omarchy-launch-webapp "https://youtube.com/"
      - key: "x"
        desc: X
        cmd: omarchy-launch-webapp "https://x.com/"
  - key: "d"
    desc: Development
    submenu:
      - key: "T"
        desc: Terminal
        cmd: uwsm-app -- xdg-terminal-exec
      - key: "t"
        desc: Tmux
        cmd: uwsm-app -- xdg-terminal-exec tmux new-session -A -s main
      - key: "n"
        desc: Editor (nvim)
        cmd: omarchy-launch-editor
      - key: "a"
        desc: Activity (btop)
        cmd: omarchy-launch-tui btop
      - key: "d"
        desc: Lazydocker
        cmd: omarchy-launch-tui lazydocker
  - key: "k"
    desc: Omarchy Keybindings
    cmd: omarchy-menu-keybindings
  - key: "s"
    desc: Screenshotting
    submenu:
      - key: "c"
        desc: capture to clipboard
        cmd: omarchy-cmd-screenshot smart clipboard
      - key: "r"
        desc: capture region to clipboard
        cmd: omarchy-cmd-screenshot region clipboard
  - key: "c"
    desc: Config
    submenu:
      - key: "a"
        desc: Audio controls
        cmd: omarchy-launch-audio
      - key: "b"
        desc: Bluetooth controls
        cmd: omarchy-launch-bluetooth
      - key: "w"
        desc: Wifi controls
        cmd: omarchy-launch-wifi
